const MIN_PLAYERS = 1;
const MAX_PLAYERS = 8;

export const da = {
  // App
  title: "Festspil",
  subtitle: "Sjove partyspil for venner og familie",

  // Landing
  createRoom: "Opret rum",
  pickGame: "Vælg et spil",
  howToPlay: "Sådan spiller du",
  startRoom: "Opret rum",
  back: "Tilbage",

  // Join
  enterCode: "Indtast rumkode",
  enterName: "Dit navn",
  join: "Deltag",
  invalidCode: "Ugyldig rumkode",
  roomNotFound: "Rummet blev ikke fundet",
  nameTaken: "Navnet er allerede taget",

  // Lobby
  waitingForHost: "Venter på værten...",
  startGame: "Start Spil",
  playersJoined: "spillere tilsluttet",
  youreIn: "Du er med!",
  needMorePlayers: `Mindst ${MIN_PLAYERS} spiller(e)`,
  roomCode: "Rumkode",

  // Game common
  timeLeft: "Tid tilbage",
  round: "Runde",
  of: "af",
  submit: "Send",
  nextRound: "Næste runde",
  scores: "Point",
  gameOver: "Spillet er slut!",
  playAgain: "Spil igen",
  backToLobby: "Tilbage til lobbyen",
  yourAnswer: "Dit svar",
  lookAtScreen: "Se op på skærmen!",
  waiting: "Venter på andre...",
  editAnswer: "Redigér svar",
  changeGame: "Skift spil",
  chooseNewGame: "Vælg nyt spil",
  noGameSelected: "Værten vælger spil...",

  // Host lines
  host: {
    letsSeePre: "Lad os se hvad I har fundet på...",
    andTheWinnerIs: "Og vinderen er...",
    closeOne: "Uh, det var tæt!",
    unanimous: "Enstemmigt! Ingen tvivl der!",
    noVotes: "Ingen stemmer? Hårdt.",
    roundIntro: (n: number, total: number) => `Runde ${n} af ${total} — gør jer klar!`,
    nextUp: "Næste svar...",
  },

  // Connection
  connectionLost: "Forbindelse mistet — genopretter...",

  // Host disconnect
  hostDisconnected: "Værten er midlertidigt frakoblet",
  waitingForHostReturn: "Venter på at værten vender tilbage...",
  leaveGame: "Forlad spil",
  roomClosed: "Spillet er lukket",
  hostLeft: "Værten har forladt spillet",
  returnToRoom: "Vend tilbage til dit rum",
  createNewRoom: "Opret nyt rum",
  leaveRoomConfirm: "Du er vært — vil du virkelig forlade rummet?",
  stayHere: "Bliv her",
  leaveAnyway: "Forlad",

  // Games
  blitz: {
    name: "Blitz",
    description: "Skriv sjove svar — stem på det bedste!",
    howToPlay: "Alle får det samme spørgsmål og skriver et sjovt svar. Derefter stemmer alle på det bedste svar — undtagen dit eget!",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • 3 runder • Tekst`,
    writeAnswer: "Skriv dit svar",
    prompt: "Spørgsmål",
    voteForBest: "Stem på det bedste svar",
    voteNowOnPhone: "Stem nu på jeres telefoner!",
    lookAtScreenForAnswers: "Se op på skærmen for alle svarene!",
    resultsAreIn: "Stemmerne er talt op...",
    winner: "Vinder",
    tieLabel: "Det er uafgjort mellem",
    quiplash: "QUIPLASH!",
  },

  fusk: {
    name: "Fusk",
    description: "Find det rigtige svar blandt løgnene",
    howToPlay: "Du får et spørgsmål med et hul — skriv et falsk svar der lyder ægte. Gæt derefter det rigtige svar mellem alle løgnene. Du scorer point for at narre andre!",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • 3 runder • Tekst`,
    writeFake: "Skriv et falsk svar",
    guessReal: "Gæt det rigtige svar",
    theRealAnswer: "Det rigtige svar",
    youFooled: "Du narrede",
    players: "spillere",
    fooledBy: "narret af",
    noOneGuessed: "Ingen gættede rigtigt!",
    yourFake: "Dit svar",
    correctGuess: "Gættede rigtigt!",
    wroteThis: "skrev dette",
  },

  scrawl: {
    name: "Scrawl",
    description: "Tegn på din telefon — andre gætter!",
    howToPlay: "Alle tegner et hemmeligt ord på telefonen. Derefter gætter de andre hvad det forestiller — skriv falske gæt for at narre! Stem på det rigtige ord.",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • 1 runde • Tegning + tekst`,
    draw: "Tegn!",
    guess: "Skriv dit gæt",
    theWordWas: "Ordet var:",
    clear: "Ryd",
    undo: "Fortryd",
    youAreTheArtist: "Du er kunstneren!",
    watchThemGuess: "Se de andre gætte på skærmen",
    whatIsBeingDrawn: "Hvad bliver der tegnet?",
    drawing: "Tegning",
    artistBonus: "Kunstnerbonus!",
    nextDrawing: "Næste tegning",
    yourGuess: "Dit gæt",
    guessReal: "Gæt det rigtige ord",
    artistWaiting: "De andre stemmer nu — vent her",
    drawingSecretWords: "Alle tegner deres hemmelige ord...",
    difficulty: "Sværhedsgrad",
    difficultyLevels: ["Let", "Medium", "Svær"] as readonly string[],
    difficultyDescriptions: [
      "Enkle ting (hest, hus, sol)",
      "Scener (en kat der sover i solen)",
      "Absurde situationer (en vampyr der er vegetar)",
    ] as readonly string[],
  },

  morph: {
    name: "Morph",
    description: "Skriv, tegn, gæt — se hvad der sker!",
    howToPlay: "Skriv en sjov sætning. Den næste tegner den, den næste gætter tegningen, den næste tegner gættet... Til sidst afsløres hele kæden — og du ser hvor galt det gik!",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • 1 runde • Tegning + tekst`,
    writePrompt: "Skriv en sjov sætning",
    writePlaceholder: "Fx: En hest der læser avisen...",
    drawThis: "Tegn dette:",
    guessThis: "Hvad forestiller tegningen?",
    everyoneIsWriting: "Alle skriver en sætning...",
    everyoneIsDrawing: "Alle tegner...",
    everyoneIsGuessing: "Alle gætter...",
    chain: "Kæde",
    of: "af",
    nextStep: "Næste",
    nextChain: "Næste kæde",
    original: "Original",
    matchBonus: "Det matchede originalen!",
  },

  surge: {
    name: "Surge",
    description: "Sandt eller falsk? Kap om at nå målet!",
    howToPlay: "Et udsagn vises på skærmen — flyt dig til SANDT eller FALSK. Se hvad de andre gør i realtid og skift side for at narre dem. Men pas på: det tager tid at skifte, og bliver du fanget midt imellem, tæller det ikke! Rigtigt svar = ét skridt fremad. Først i mål vinder!",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • Uendelige runder • Videns-quiz`,
    sandt: "Sandt",
    falsk: "Falsk",
    transit: "Skifter side...",
    correct: "Rigtigt!",
    wrong: "Forkert!",
    noAnswer: "Du nåede ikke at vælge!",
    position: "Position",
    finish: "Mål",
    winner: "I mål!",
    sharedWin: "Delt sejr!",
    getReady: "Gør jer klar!",
    statement: "Påstand",
    lookAtScreenForChoices: "Se op — hvem skifter side?",
    difficulty: "Sværhedsgrad",
    difficultyLevels: ["Let", "Medium", "Svær"] as readonly string[],
    difficultyDescriptions: [
      "Simpelt (LEGO, dyr, popkultur)",
      "Almenviden (geografi, historie)",
      "Tricky myter og fakta",
    ] as readonly string[],
  },

  hunch: {
    name: "Hunch",
    description: "Giv et fingerpeg — andre gætter positionen!",
    howToPlay: "En spiller ser en hemmelig position på et spektrum og giver et fingerpeg. Alle andre gætter positionen. Jo tættere på, jo flere point!",
    expects: `${MIN_PLAYERS}–${MAX_PLAYERS} spillere • Roterende runder • Tekst`,
    youAreClueGiver: "Du giver fingerpeget!",
    writeClue: "Skriv dit fingerpeg",
    cluePlaceholder: "Ét ord eller kort sætning...",
    waitingForClue: "skriver et fingerpeg...",
    clueIs: "Fingerpeget er",
    placeGuess: "Placer dit gæt",
    submitGuess: "Send gæt",
    editGuess: "Redigér gæt",
    watchingGuesses: "Venter på de andres gæt...",
    targetWas: "Positionen var",
    exact: "Præcist!",
    close: "Meget tæt!",
    near: "Næsten!",
    miss: "Ikke helt...",
    clueGiverBonus: "Fingerpeger-bonus",
    yourScore: "Dine point",
  },

  // External games
  externalGames: "Bonusspil",
  opensNewTab: "Åbner i nyt faneblad",
  pris: {
    name: "Pris-quiz",
    description: "Gæt prisen på brugte ting fra DBA",
  },
} as const;
